initial_capital: 10000

# Database Configuration
database:
  host: "localhost"
  port: 5432
  database: "algo_trade_db"
  username: "user"
  password: "user"
  # database:
  # host: "ykt-piserver.zapto.org"
  # port: 5432
  # database: "algo_trade_db"
  # username: "kaitsunyip"
  # password: "P@ssword1"

# Trading System State Configuration
system_state:
  mode: "live"  # Options: "live", "backtest", "paper"
  active_strategies:
    - "zscore"  
    - "rsi"

# Trading Strategy Configuration
strategies:
  # Z-Score Strategy Parameters
  zscore:
    window: 90
    threshold: 2.25
    position_size: 0.1

  # RSI Strategy Parameters
  rsi:
    # Core Parameters
    window: 30
    overbought: 20
    oversold: 80
    position_size: 0.1
