alpha_vantage_api_key: 12NGKM9P6N4YJ2Z5
initial_capital: 10000
# Trading System State Configuration
system_state:
  mode: "live"  # Options: "live", "backtest", "paper"
  active_strategies:
    - "zscore"  
    - "rsi"

# Trading Strategy Configuration
strategies:
  # Z-Score Strategy Parameters
  zscore:
    window: 90
    threshold: 2.25
    position_size: 0.1

  # RSI Strategy Parameters
  rsi:
    # Core Parameters
    window: 30
    overbought: 20
    oversold: 80
    position_size: 0.1
